# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: newvariable

stages:

- stage: store the code
  displayName: Storing git files
  jobs:
  - job: store github files
    pool:
      vmImage: $(os)
    
    steps:
      - task: CopyFiles@2
        displayName: Store github files in folder
        inputs:
          Contents: '**'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: Store it in a folder
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'githubcode'
          publishLocation: 'Container'

- stage: build the .net app
  displayName: Build .net
  jobs:
  - job: Build
    pool:
      vmImage: $(os)
    steps:
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
      - task: CopyFiles@2
        inputs:
          Contents: '**'
          TargetFolder: '$(build.artifactstagingdirectory)'
 
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
